export const BOOKINGS_SET_DATE = 'BOOKINGS_SET_DATE'
export const BOOKINGS_SET_DATE_ERROR = 'BOOKINGS_SET_DATE_ERROR'

export const BOOKINGS_REQUEST = 'BOOKINGS_REQUEST'
export const BOOKINGS_SUCCESS = 'BOOKINGS_SUCCESS'
export const BOOKINGS_ERROR   = 'BOOKINGS_ERROR'
export const BOOKINGS_SORT    = 'BOOKINGS_SORT'
export const BOOKINGS_CREATE  = 'BOOKINGS_CREATE'
export const BOOKINGS_UPDATE  = 'BOOKINGS_UPDATE'

export const BOOKINGS_PUSH    = 'BOOKINGS_PUSH'
export const BOOKINGS_REMOVE  = 'BOOKINGS_REMOVE'
